### ISSUE TITLE
Intégration Page Accueil

### ISSUE THREAD

**Issue by youcoder-ma** [youcoder-ma/Covidiot#2]

**Comment by youcoder-ma** [comment]
page accueil ok

**Comment by imanegannaoui** [comment]
J'ai réouvert cet issue par ce que la page vous devez changer la couleur du background de la page d'accueil , elle est en rouge, 
par contre les autres sections sont parfaites

**Comment by imanegannaoui** [comment]
la page d'accueil est validée
